wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.14.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1680767681.435653
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      4: 3.9.13
      5: 0.14.1
      8:
      - 3
      - 5
